
<<<
[[section_run_taiko_code_outside_of_the_repl]]
=== Run Taiko Code Outside of the REPL
[source, shell]
----
$ taiko visit-wikipedia.js

 ✔ Browser opened
 ✔ Navigated to URL http://wikipedia.org
 ✔ Browser closed
----

When you type `taiko` without a filename, it launches the Taiko REPL. When you type `taiko visit-wikipedia.js`, it runs the Taiko commands in the file. 

You might have noticed that typing `openBrowser()` in the Taiko REPL actually opens a browser that you can see. By default, running Taiko commands outside of the REPL runs the browser in "headless mode". This means that the browser isn't actually shown on screen, but its behavior in headless mode is identical to its behavior with a visible browser. This is ideal for running Taiko commands in an automated server environment where there most likely isn't a screen to display the progress.  

If you'd like to see the browser when running Taiko commands outside of the REPL, type `taiko --observe visit-wikipedia.js`. The `--observe` command-line flag, in addition to showing the browser, also inserts a 3 second (3000 millisecond) delay between steps to make them easier to observe. If you'd like to adjust this delay, use the `--wait-time` command-line flag -- `taiko --observe --wait-time 1000 visit-wikipedia.js`.


