
<<<
[[section_getting_command_line_help]]
=== Getting Command-Line Help
[source, shell]
----
$ taiko --help

Usage: taiko [options]
       taiko <file> [options]

Options:
  -v, --version                    output the version number

  -o, --observe                    enables headful mode and runs 
                                   script with 3000ms delay by 
                                   default. pass --wait-time 
                                   option to override the default 
                                   3000ms
  
  -l, --load                       run the given file and start the 
                                   repl to record further steps.

  -w, --wait-time <time in ms>     runs script with provided delay
  
  --emulate-device <device>        Allows to simulate device 
                                   viewport. 
                                   Visit https://github.com/getgauge/
                                   taiko/blob/master/lib/devices.js
                                   for all the available devices
  
  --emulate-network <networkType>  Allow to simulate network. 
                                   Available options are GPRS,
                                   Regular2G, Good2G, Regular3G, 
                                   Good3G, Regular4G, DSL,
                                   WiFi, Offline
  
  --plugin <plugin1,plugin2...>    Load the taiko plugin.
  
  --no-log                         Disable log output of taiko
  
  -h, --help                       display help for command
----

There are a number of command-line flags that affect Taiko at runtime. `--observe` and `--wait-time` allow you to see the browser as the Taiko commands are performed. (Normally, Taiko runs in "headless mode" at the command-line.)

You can use `--emulate-device` and `--emulate-network` to simulate smartphone usage. 

`--load` allows you to preload the Taiko REPL with commands stored in a file. 

`--plugin` allows you to load Taiko plugins that extend native behavior. 


