
<<<
[[section_save_code_from_the_taiko_repl]]
=== Save Code from the Taiko REPL
[source, shell]
----
$ taiko

> openBrowser()
 ✔ Browser opened
> goto('wikipedia.org')
 ✔ Navigated to URL http://wikipedia.org
> closeBrowser()
 ✔ Browser closed
> .code

const { openBrowser, goto, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto('wikipedia.org');
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();

// If you provide a filename, 
//   .code saves your code to the current directory
> .code visit-wikipedia.js 
----

At any point in the Taiko REPL, you can type `.code` to see what the JavaScript will look like once you run your Taiko code outside of the REPL. Notice that this is modern asynchronous JavaScript -- every command will `await` completion before moving on to the next step. 

If you'd like to save this code for running outside of the REPL, simply provide a filename like `.code visit-wikipedia.js`. This will save the JavaScript code to the current directory.


